### ISSUE TITLE
Remove entrypoint.sh script for Database Initialization

### ISSUE THREAD

**Issue by shantanoo-desai** [Anaisdg/InfluxDBv2_Telegraf_Docker#4]
## Description
As it turns out, one does not need to provision the Database via `entrypoint.sh` script. This can be done by just providing the following environment variables to telegraf:

```bash
DOCKER_INFLUXDB_INIT_ORG
DOCKER_INFLUXDB_INIT_BUCKET
DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
```
## Tests
Following compose file is tested for 

- __InfluxDB v2.1.1-alpine__
- __Telegraf v1.22-alpine__

```yaml
version: '3.7'

services:
  influxdb:
    image: influxdb:2.1.1-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: Edgy
      DOCKER_INFLUXDB_INIT_BUCKET: data
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: edgestack
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: edgestack
    security_opt:
      - "no-new-privileges:true"

  telegraf:
    image: telegraf:1.22-alpine
    container_name: telegraf
    depends_on:
      - influxdb
    environment:
      DOCKER_INFLUXDB_INIT_ORG: Edgy
      DOCKER_INFLUXDB_INIT_BUCKET: data
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: edgestack
    volumes:
      - ./telegraf/telegraf.toml:/etc/telegraf/telegraf.conf:ro
    security_opt:
      - "no-new-privileges:true"
 ```
